#!/bin/sh

ENV_FILES=$(git diff --cached --name-only | grep -E "^\.env")

if [ -n "$ENV_FILES" ]; then
  echo "$ENV_FILES"

  for f in $ENV_FILES; do
    git restore --staged "$f"
    echo "   $f убран из коммита"
  done

fi

