#!/bin/sh

# Запрет пуша в main/master
BRANCH=$(git branch --show-current)
if [ "$BRANCH" = "main" ] || [ "$BRANCH" = "master" ]; then
  echo " Нельзя пушить напрямую в $BRANCH!"
  echo "Необходимосоздать отдельную ветку: git checkout -b feature/my-feature"
  exit 1
fi


golangci-lint run
if [ $? -ne 0 ]; then
  echo "Линтер нашёл ошибки. "
  exit 1
fi
echo "Линтер прошёл успешно."


echo "Запускаем тесты..."
go test ./...
if [ $? -ne 0 ]; then
  echo "Тесты упали. Пуш отменён."
  exit 1
fi

